# Generated by Django 4.1.2 on 2022-11-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=2000)),
                ('fecha_de_inscripcion', models.CharField(max_length=100)),
                ('promedio', models.IntegerField()),
                ('id_universidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostulantesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('contacto', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Universidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localizacion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('descripcion', models.CharField(max_length=2000)),
                ('contacto', models.EmailField(max_length=100)),
            ],
        ),
    ]
