# Generated by Django 4.1.2 on 2022-11-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Becas_Universitarias', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Universidades',
            new_name='UniversidadesModel',
        ),
    ]
