# Generated by Django 4.1.2 on 2022-11-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Becas_Universitarias', '0002_rename_universidades_universidadesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantesmodels',
            name='contacto',
            field=models.TextField(),
        ),
    ]
