# Generated by Django 4.1 on 2022-11-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Becas_Universitarias', '0003_alter_postulantesmodels_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantesmodels',
            name='contacto',
            field=models.IntegerField(),
        ),
    ]
